/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persondigitalassistentapp.view;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import persondigitalassistentapp.controller.PersonalDigitalAssistentController;
import persondigitalassistentapp.model.Contacto;

/**
 *
 * @author alvar
 */
public class BuscarContactoView extends javax.swing.JFrame {

    /**
     * Creates new form Contactos
     */
    public BuscarContactoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPantalla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonBuscar2 = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonMenu1 = new javax.swing.JMenu();
        botonContactos1 = new javax.swing.JMenu();
        botonRegistrar1 = new javax.swing.JMenuItem();
        botonEditar1 = new javax.swing.JMenuItem();
        botonEliminar = new javax.swing.JMenuItem();
        botonRegistro1 = new javax.swing.JMenu();
        botonBuscar1 = new javax.swing.JMenuItem();
        botonVisualizar1 = new javax.swing.JMenuItem();
        botonAyuda1 = new javax.swing.JMenu();
        botonAcercaDe1 = new javax.swing.JMenu();
        botonPersonal1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Busqueda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el email del contacto que desea buscar.");

        botonBuscar2.setBackground(new java.awt.Color(204, 102, 255));
        botonBuscar2.setText("Buscar");
        botonBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar2ActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(204, 102, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 255)));

        botonMenu1.setText("Menu");

        botonContactos1.setText("Contactos");

        botonRegistrar1.setText("Registrar");
        botonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonRegistrar1);

        botonEditar1.setText("Editar");
        botonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEditar1);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEliminar);

        botonMenu1.add(botonContactos1);

        botonRegistro1.setText("Registro");

        botonBuscar1.setText("Buscar");
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonBuscar1);

        botonVisualizar1.setText("Visualizar");
        botonVisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVisualizar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonVisualizar1);

        botonMenu1.add(botonRegistro1);

        jMenuBar1.add(botonMenu1);

        botonAyuda1.setText("Ayuda");

        botonAcercaDe1.setText("Acerca de");

        botonPersonal1.setText("Personal Digital Assistent");
        botonPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonal1ActionPerformed(evt);
            }
        });
        botonAcercaDe1.add(botonPersonal1);

        botonAyuda1.add(botonAcercaDe1);

        jMenuBar1.add(botonAyuda1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(botonBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String nombre;
    String email;
    String telefono;
    int id;
    
    
    private void botonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrar1ActionPerformed
        PersonalDigitalAssistentController.onNuevoContactoView();
        PersonalDigitalAssistentController.offBuscarContactoView();
    }//GEN-LAST:event_botonRegistrar1ActionPerformed

    private void botonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditar1ActionPerformed
        PersonalDigitalAssistentController.onEditarContactoView();
        PersonalDigitalAssistentController.offBuscarContactoView();

    }//GEN-LAST:event_botonEditar1ActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        PersonalDigitalAssistentController.onEliminarContactoView();
        PersonalDigitalAssistentController.offBuscarContactoView();

    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed


    }//GEN-LAST:event_botonBuscar1ActionPerformed

    private void botonVisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVisualizar1ActionPerformed
        PersonalDigitalAssistentController.onListaDeContatosView();
        PersonalDigitalAssistentController.offBuscarContactoView();

    }//GEN-LAST:event_botonVisualizar1ActionPerformed

    private void botonPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonal1ActionPerformed
        PersonalDigitalAssistentController.onPersonalDigitalAssistentView();
        PersonalDigitalAssistentController.offBuscarContactoView();

    }//GEN-LAST:event_botonPersonal1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        PersonalDigitalAssistentController.offBuscarContactoView();
        PersonalDigitalAssistentController.onFirstView();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar2ActionPerformed
        
        String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern EMAIL_PATTERN = Pattern.compile(EMAIL_REGEX);
        email = txtPantalla.getText();
        if(email != null & !(email.isEmpty())){
        
            if(EMAIL_PATTERN.matcher(email).matches()){
                
                
                id = Contacto.searchContacto(email);
                if(id >=0){
                    Contacto cont = Contacto.verContacto(id);
                
                    int opcion = JOptionPane.showConfirmDialog(
                        null,
                        "¿Es este el email del contacto?\n\n" + email,
                        "Verificar email",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.INFORMATION_MESSAGE
                    );

                // Manejar la respuesta del usuario
                    if (opcion == JOptionPane.OK_OPTION) {
                        String datosDeContacto =  "<html>Nombre:"+ cont.getNombre()+"<br>"
                        + "Email:"+cont.getEmail()+"<br>"
                        + "Teléfono:"+ cont.getTelefono()+"<br>";
                        JOptionPane.showMessageDialog(
                            null,
                            "Has aceptado el email: " + email,
                            "Confirmación",
                            JOptionPane.INFORMATION_MESSAGE
                        );
                        
                        JOptionPane.showMessageDialog(
                                null, datosDeContacto, "Detalles", 
                                JOptionPane.INFORMATION_MESSAGE
                        );
                        
                    } else{
                        JOptionPane.showMessageDialog(
                           null,
                           "Has cancelado la selección.",
                           "Operación cancelada",
                           JOptionPane.WARNING_MESSAGE
                        );
                    }
                }else{
                    
                     JOptionPane.showMessageDialog(
                         
                        this,
                        "Email no encontrado" ,
                        "Intente nuevamente.\n",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    
                
                }  
                email="";
                txtPantalla.setText("");
            }
        }else{
        
        
            JOptionPane.showMessageDialog(
                         
                    this,
                    "Email no ingresado" ,
                    "Ingrese el email.\n",
                    JOptionPane.WARNING_MESSAGE
                );
                email = "";
                txtPantalla.setText("");
           

        }
        
        
        
    }//GEN-LAST:event_botonBuscar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarContactoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botonAcercaDe1;
    private javax.swing.JMenu botonAyuda1;
    private javax.swing.JMenuItem botonBuscar1;
    private javax.swing.JButton botonBuscar2;
    private javax.swing.JMenu botonContactos1;
    private javax.swing.JMenuItem botonEditar1;
    private javax.swing.JMenuItem botonEliminar;
    private javax.swing.JMenu botonMenu1;
    private javax.swing.JMenuItem botonPersonal1;
    private javax.swing.JMenuItem botonRegistrar1;
    private javax.swing.JMenu botonRegistro1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuItem botonVisualizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
