/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persondigitalassistentapp.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persondigitalassistentapp.controller.PersonalDigitalAssistentController;
import persondigitalassistentapp.cruddata.PersonalDigitalAssistentDao;
import persondigitalassistentapp.model.Contacto;

/**
 *
 * @author alvar
 */
public class EditarContactoView extends javax.swing.JFrame {

    /**
     * Creates new form EditorContactoView
     */
    public EditarContactoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonAceptar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonMenu1 = new javax.swing.JMenu();
        botonContactos1 = new javax.swing.JMenu();
        botonRegistrar1 = new javax.swing.JMenuItem();
        botonEditar1 = new javax.swing.JMenuItem();
        botonEliminar1 = new javax.swing.JMenuItem();
        botonRegistro1 = new javax.swing.JMenu();
        botonBuscar = new javax.swing.JMenuItem();
        botonVisualizar = new javax.swing.JMenuItem();
        botonAyuda1 = new javax.swing.JMenu();
        botonAcercaDe = new javax.swing.JMenu();
        botonPersonal = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Edición de Contacto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Email", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botonAceptar.setBackground(new java.awt.Color(102, 255, 102));
        botonAceptar.setText("Editar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(102, 255, 102));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Has clik en la fila del contacto que desea editar.");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));

        botonMenu1.setText("Menu");

        botonContactos1.setText("Contactos");

        botonRegistrar1.setText("Registrar");
        botonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonRegistrar1);

        botonEditar1.setText("Editar");
        botonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEditar1);

        botonEliminar1.setText("Eliminar");
        botonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEliminar1);

        botonMenu1.add(botonContactos1);

        botonRegistro1.setText("Registro");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonBuscar);

        botonVisualizar.setText("Visualizar");
        botonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVisualizarActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonVisualizar);

        botonMenu1.add(botonRegistro1);

        jMenuBar1.add(botonMenu1);

        botonAyuda1.setText("Ayuda");

        botonAcercaDe.setText("Acerca de");

        botonPersonal.setText("Personal Digital Assistent");
        botonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalActionPerformed(evt);
            }
        });
        botonAcercaDe.add(botonPersonal);

        botonAyuda1.add(botonAcercaDe);

        jMenuBar1.add(botonAyuda1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int fila = 0;
    
    private void botonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrar1ActionPerformed
        
        PersonalDigitalAssistentController.onNuevoContactoView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonRegistrar1ActionPerformed

    private void botonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditar1ActionPerformed
        
        PersonalDigitalAssistentController.onEditarContactoView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonEditar1ActionPerformed

    private void botonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar1ActionPerformed
        PersonalDigitalAssistentController.onEliminarContactoView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonEliminar1ActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        PersonalDigitalAssistentController.onBuscarContactoView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVisualizarActionPerformed
        PersonalDigitalAssistentController.onListaDeContatosView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonVisualizarActionPerformed

    private void botonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalActionPerformed
        PersonalDigitalAssistentController.onPersonalDigitalAssistentView();
        PersonalDigitalAssistentController.offEditarContactoView();
    }//GEN-LAST:event_botonPersonalActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        PersonalDigitalAssistentController.offEditarContactoView();
        PersonalDigitalAssistentController.onFirstView();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        fila = jTable1.getSelectedRow();

        if(fila !=-1){
        
            
            int id = (int) jTable1.getValueAt(fila, 0);   
            System.out.println(id);
            Contacto c = PersonalDigitalAssistentDao.buscarPorId(id);
           
            Contacto.addContacto(c);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
        
        if(fila !=-1){
        
            PersonalDigitalAssistentController.onEdicionView();
            PersonalDigitalAssistentController.offEditarContactoView();
            fila = -1;
            
        
        }else{
        
            JOptionPane.showMessageDialog(this, "Debes seleccionar un contacto.");
        
        
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    public void mostrarDatos(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        List<Contacto> contactos = new ArrayList<>();
        contactos = PersonalDigitalAssistentDao.getAll();
    
        for (Contacto c : contactos) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getEmail(),
                c.getTelefono()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarContactoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JMenu botonAcercaDe;
    private javax.swing.JMenu botonAyuda1;
    private javax.swing.JMenuItem botonBuscar;
    private javax.swing.JMenu botonContactos1;
    private javax.swing.JMenuItem botonEditar1;
    private javax.swing.JMenuItem botonEliminar1;
    private javax.swing.JMenu botonMenu1;
    private javax.swing.JMenuItem botonPersonal;
    private javax.swing.JMenuItem botonRegistrar1;
    private javax.swing.JMenu botonRegistro1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuItem botonVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
