/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persondigitalassistentapp.view;

import persondigitalassistentapp.controller.PersonalDigitalAssistentController;

/**
 *
 * @author alvar
 */
public class FirstView extends javax.swing.JFrame {

    /**
     * Creates new form FirstNew
     */
    public FirstView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonContactos2 = new javax.swing.JButton();
        botonRegistro2 = new javax.swing.JButton();
        botonAcercaDe2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonMenu = new javax.swing.JMenu();
        botonContactos1 = new javax.swing.JMenu();
        botonRegistrar1 = new javax.swing.JMenuItem();
        botonEditar1 = new javax.swing.JMenuItem();
        botonEliminar1 = new javax.swing.JMenuItem();
        botonRegistro1 = new javax.swing.JMenu();
        botonBuscar1 = new javax.swing.JMenuItem();
        botonVisualizar1 = new javax.swing.JMenuItem();
        botonAyuda = new javax.swing.JMenu();
        botonAcercaDe1 = new javax.swing.JMenu();
        botonPersonal1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Personal Digital Assistent");

        botonContactos2.setBackground(new java.awt.Color(102, 153, 255));
        botonContactos2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonContactos2.setText("Contactos");
        botonContactos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContactos2ActionPerformed(evt);
            }
        });

        botonRegistro2.setBackground(new java.awt.Color(102, 153, 255));
        botonRegistro2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro2.setText("Registro");
        botonRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistro2ActionPerformed(evt);
            }
        });

        botonAcercaDe2.setBackground(new java.awt.Color(102, 153, 255));
        botonAcercaDe2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAcercaDe2.setText("Acerca de");
        botonAcercaDe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcercaDe2ActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));

        botonMenu.setText("Menú");

        botonContactos1.setText("Contactos");

        botonRegistrar1.setText("Registrar");
        botonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonRegistrar1);

        botonEditar1.setText("Editar");
        botonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEditar1);

        botonEliminar1.setText("Eliminar");
        botonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEliminar1);

        botonMenu.add(botonContactos1);

        botonRegistro1.setText("Registro");

        botonBuscar1.setText("Buscar");
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonBuscar1);

        botonVisualizar1.setText("Visualizar");
        botonVisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVisualizar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonVisualizar1);

        botonMenu.add(botonRegistro1);

        jMenuBar1.add(botonMenu);

        botonAyuda.setText("Ayuda");

        botonAcercaDe1.setText("Acerca de");

        botonPersonal1.setText("Personal Digital Assistent");
        botonPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonal1ActionPerformed(evt);
            }
        });
        botonAcercaDe1.add(botonPersonal1);

        botonAyuda.add(botonAcercaDe1);

        jMenuBar1.add(botonAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonContactos2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(botonRegistro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAcercaDe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(botonContactos2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botonRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonAcercaDe2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void botonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditar1ActionPerformed
             
        PersonalDigitalAssistentController.onEditarContactoView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonEditar1ActionPerformed

    private void botonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrar1ActionPerformed

        PersonalDigitalAssistentController.onNuevoContactoView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonRegistrar1ActionPerformed

    private void botonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar1ActionPerformed

        PersonalDigitalAssistentController.onEliminarContactoView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonEliminar1ActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
        PersonalDigitalAssistentController.onBuscarContactoView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonBuscar1ActionPerformed

    private void botonVisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVisualizar1ActionPerformed
        PersonalDigitalAssistentController.onListaDeContatosView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonVisualizar1ActionPerformed

    private void botonContactos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContactos2ActionPerformed
        PersonalDigitalAssistentController.onMenuContactosView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonContactos2ActionPerformed

    private void botonRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistro2ActionPerformed
        PersonalDigitalAssistentController.onMenuRegistroView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonRegistro2ActionPerformed

    private void botonPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonal1ActionPerformed
        PersonalDigitalAssistentController.onPersonalDigitalAssistentView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonPersonal1ActionPerformed

    private void botonAcercaDe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDe2ActionPerformed
        PersonalDigitalAssistentController.onPersonalDigitalAssistentView();
        PersonalDigitalAssistentController.offFirstView();
    }//GEN-LAST:event_botonAcercaDe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botonAcercaDe1;
    private javax.swing.JButton botonAcercaDe2;
    private javax.swing.JMenu botonAyuda;
    private javax.swing.JMenuItem botonBuscar1;
    private javax.swing.JMenu botonContactos1;
    private javax.swing.JButton botonContactos2;
    private javax.swing.JMenuItem botonEditar1;
    private javax.swing.JMenuItem botonEliminar1;
    private javax.swing.JMenu botonMenu;
    private javax.swing.JMenuItem botonPersonal1;
    private javax.swing.JMenuItem botonRegistrar1;
    private javax.swing.JMenu botonRegistro1;
    private javax.swing.JButton botonRegistro2;
    private javax.swing.JMenuItem botonVisualizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
