/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persondigitalassistentapp.view;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import persondigitalassistentapp.controller.PersonalDigitalAssistentController;
import persondigitalassistentapp.model.Contacto;

/**
 *
 * @author alvar
 */
public class NuevoContactoView extends javax.swing.JFrame {

    /**
     * Creates new form NuevoContactoView
     */
    public NuevoContactoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPantallaNombre = new javax.swing.JTextField();
        txtPantallaEmail = new javax.swing.JTextField();
        txtPantallaTelefono = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonMenu1 = new javax.swing.JMenu();
        botonContactos1 = new javax.swing.JMenu();
        botonRegistrar1 = new javax.swing.JMenuItem();
        botonEditar1 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        botonRegistro1 = new javax.swing.JMenu();
        botonBuscar1 = new javax.swing.JMenuItem();
        botonVisualizar1 = new javax.swing.JMenuItem();
        botonAyuda1 = new javax.swing.JMenu();
        botonAcercaDe1 = new javax.swing.JMenu();
        botonPersonal1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nuevo Contacto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono:");

        botonAceptar.setBackground(new java.awt.Color(153, 153, 255));
        botonAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(153, 153, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));

        botonMenu1.setText("Menu");

        botonContactos1.setText("Contactos");

        botonRegistrar1.setText("Registrar");
        botonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonRegistrar1);

        botonEditar1.setText("Editar");
        botonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditar1ActionPerformed(evt);
            }
        });
        botonContactos1.add(botonEditar1);

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        botonContactos1.add(jMenuItem1);

        botonMenu1.add(botonContactos1);

        botonRegistro1.setText("Registro");

        botonBuscar1.setText("Buscar");
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonBuscar1);

        botonVisualizar1.setText("Visualizar");
        botonVisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVisualizar1ActionPerformed(evt);
            }
        });
        botonRegistro1.add(botonVisualizar1);

        botonMenu1.add(botonRegistro1);

        jMenuBar1.add(botonMenu1);

        botonAyuda1.setText("Ayuda");

        botonAcercaDe1.setText("Acerca de");

        botonPersonal1.setText("Personal Digital Assistent");
        botonAcercaDe1.add(botonPersonal1);

        botonAyuda1.add(botonAcercaDe1);

        jMenuBar1.add(botonAyuda1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPantallaNombre)
                            .addComponent(txtPantallaEmail)
                            .addComponent(txtPantallaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPantallaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPantallaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPantallaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    String nombre;
    String email;
    String telefono;
    
    private void botonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrar1ActionPerformed
        
        
    }//GEN-LAST:event_botonRegistrar1ActionPerformed

    private void botonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditar1ActionPerformed
        PersonalDigitalAssistentController.onEditarContactoView();
        PersonalDigitalAssistentController.offNuevoContactoView();
    }//GEN-LAST:event_botonEditar1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PersonalDigitalAssistentController.onEliminarContactoView();
        PersonalDigitalAssistentController.offNuevoContactoView();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
        PersonalDigitalAssistentController.onBuscarContactoView();
        PersonalDigitalAssistentController.offNuevoContactoView();
    }//GEN-LAST:event_botonBuscar1ActionPerformed

    private void botonVisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVisualizar1ActionPerformed
        PersonalDigitalAssistentController.onListaDeContatosView();
        PersonalDigitalAssistentController.offNuevoContactoView();

    }//GEN-LAST:event_botonVisualizar1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        PersonalDigitalAssistentController.offNuevoContactoView();
        PersonalDigitalAssistentController.onFirstView();

    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
       
       String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
       Pattern EMAIL_PATTERN = Pattern.compile(EMAIL_REGEX);
       String PHONE_REGEX = "^(\\+?\\d[\\d\\s-]{4,13}\\d)$";
       nombre =  txtPantallaNombre.getText();
       email = txtPantallaEmail.getText();
       telefono = txtPantallaTelefono.getText();
       
       if(!(nombre.isEmpty()) && !(email.isEmpty()) && !(telefono.isEmpty())){
       
            if(!(nombre == null) || !(email == null) || !(telefono == null)){

                if(EMAIL_PATTERN.matcher(email).matches()){
                    
                    if(telefono.matches(PHONE_REGEX)){
                        Contacto.addContacto(new Contacto(nombre,email,telefono));
                        System.out.println(Contacto.getContactos());
                        JOptionPane.showMessageDialog(
                        this,
                        "Proceso exitoso" ,
                        "Los datos ingresados fueron registrados.\n",
                        JOptionPane.INFORMATION_MESSAGE
                        );
                    
                        nombre = "";
                        email = "";
                        telefono = "";
                        txtPantallaNombre.setText("");
                        txtPantallaEmail.setText("");
                        txtPantallaTelefono.setText("");
                    }else{
                    
                        JOptionPane.showMessageDialog(
                         
                        this,
                        "Numero de telefono no válido (6-14 digitos)" ,
                        "Ingrese nuevamente el número.\n",
                        JOptionPane.WARNING_MESSAGE
                                
                        );
                        telefono = "";
                        txtPantallaTelefono.setText("");
                    }

                }else{
                
                    JOptionPane.showMessageDialog(
                         
                        this,
                        "Email no válido" ,
                        "Ingrese nuevamente el email.\n",
                        JOptionPane.WARNING_MESSAGE
                    );
                    email = "";
                    txtPantallaEmail.setText("");
                
                }
               
            }else{
       
                    JOptionPane.showMessageDialog(
                         
                        this,
                        "Proceso denegado" ,
                        "Ingrese los datos de cada compo.\n",
                        JOptionPane.WARNING_MESSAGE
                    );
            }
        }else{
       
       
            JOptionPane.showMessageDialog(
                         
                this,
                "Proceso denegado" ,
                "Ingrese los datos de cada compo.\n",
                JOptionPane.WARNING_MESSAGE
            );
            nombre = "";
            email = "";
            telefono = "";
            txtPantallaNombre.setText("");
            txtPantallaEmail.setText("");
            txtPantallaTelefono.setText("");
       }
 
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoContactoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JMenu botonAcercaDe1;
    private javax.swing.JMenu botonAyuda1;
    private javax.swing.JMenuItem botonBuscar1;
    private javax.swing.JMenu botonContactos1;
    private javax.swing.JMenuItem botonEditar1;
    private javax.swing.JMenu botonMenu1;
    private javax.swing.JMenuItem botonPersonal1;
    private javax.swing.JMenuItem botonRegistrar1;
    private javax.swing.JMenu botonRegistro1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuItem botonVisualizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtPantallaEmail;
    private javax.swing.JTextField txtPantallaNombre;
    private javax.swing.JTextField txtPantallaTelefono;
    // End of variables declaration//GEN-END:variables
}
